config/routes.rb
Rails.application.routes.draw do

  # devise_for :users
  #
  # devise_for :users, controllers: {
  #   # confirmations: 'users/confirmations'
  #   confirmations: 'users/confirmations',
  #   registrations: 'users/registrations',
  #   sessions: 'users/sessions'
  # }


  # devise_for :users, skip: [:registrations]
  devise_for :users, skip: [:registrations], controllers: {
    # confirmations: 'users/confirmations'
    confirmations: 'users/confirmations',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  as :user do
    # get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    # put 'users' => 'devise/registrations#update', :as => 'user_registration'

    get 'users/edit' => 'users/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'users/registrations#update', :as => 'user_registration'
  end

  resources :contacts do
    get :block_contact, on: :member
    get :unblock_contact, on: :member
  end
  resources :skills
  resources :references
  resources :samples

  # Royal Ciinema
  resources :auditoriums

  # The extra_pages view (extra)
  get 'pages', to: 'pages#index'

  # root :to => redirect("/pages")
  root to: redirect("pages")
end

app/models/sample.rb
class Sample < ApplicationRecord

  # Attachments
  has_one_attached :image, dependent: :destroy

  # Validations:
  validates :title, presence: true
  validates :sub_title, presence: true
  validates :url, presence: true

end

app/controllers/samples_controller.rb
class SamplesController < ApplicationController

  include CommonControl

  before_action :authenticate_user!
  before_action :set_sample, only: %i[show edit update destroy]
  before_action :update_concerned_path, only: [:new, :create, :edit, :update]

  def index
    samples_scope = Sample.all
    @samples_scope_meta = samples_scope.ransack(@scope)
    @samples_scope_meta.sorts = "#{@sort_column} #{@sort_direction}" if @samples_scope_meta.sorts.empty?
    @pagy, @samples = pagy(@samples_scope_meta.result, items: 10)
  end

  def show; end

  def new
    @sample = Sample.new
  end

  def edit
  end

  def create
    @sample = sample_service.build_sample(sample_params)

    if @sample.save
      redirect_notice = t('samples.create.success_notice')
      redirect_to @return_to, notice: redirect_notice
    else
      flash[:alert] = @sample.errors.full_messages.first
      render :new
    end
  end

  def update
    @sample = sample_service.update_sample(sample_params.merge(id: params.fetch(:id)))

    if @sample.save
      redirect_notice = t('samples.update.success_notice')
      redirect_to @return_to, notice: redirect_notice
    else
      flash[:alert] = @sample.errors.full_messages.first
      render action: :edit
    end
  end

  def destroy
    @sample.destroy
    respond_to do |format|
      format.html { redirect_to samples_url, notice: t('samples.destroy.success_notice') }
      format.json { head :no_content }
    end
  end

  private

  def sample_service
    SampleService
  end

  def set_sample
    @sample = Sample.all.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def sample_params
    params.fetch(:sample, {}).permit(:title, :sub_title, :url, :image)
  end

end

app/helpers/samples_helper.rb
module SamplesHelper
end

app/views/samples/_form.html.erb
<%
  sample_model = Sample
  sample = local_assigns.fetch(:sample, Sample.new)
  return_to = local_assigns.fetch(:return_to, request.fullpath)

  # binding.pry
%>

<div class="card-body">
  <%= form_with(model: sample, local: true) do |form| %>
    <%= hidden_field_tag :return_to, return_to %>

    <div class="form-row">
      <div class="col-md-6">
        <div class="form-group">
          <%= form.label :title, humanize_attribute(sample_model, :title), class: 'small mb-1' %>
          <%= form.text_field :title, class: 'form-control py-4', autofocus: true, autocomplete: "title", placeholder: 'Enter the title' %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <%= form.label :sub_title, humanize_attribute(sample_model, :sub_title), class: 'small mb-1' %>
          <%= form.text_field :sub_title, class: 'form-control py-4', autofocus: true, autocomplete: "sub_title", placeholder: 'Enter the sub title' %>
        </div>
      </div>
    </div>

    <div class="form-row">
      <div class="col-md-6">
        <div class="form-group">
          <%= form.label :url, humanize_attribute(sample_model, :url), class: 'small mb-1' %>
          <%= form.text_field :url, class: 'form-control py-4', autofocus: true, autocomplete: "url", placeholder: 'Enter the url' %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <%= form.label :image, humanize_attribute(sample_model, :image), class: 'small mb-1' %>
          <small style="font-size: x-small;">(<%= t('samples.form.image_format') %>)</small>
          <%= form.file_field :image, class: 'form-control f-image-preview-input', style: 'height: 50px;', accept: 'image/png, image/jpg, image/jpeg, image/gif' %>
          <br>
          <% if sample.image.attached? %>
            <%= image_tag sample.image, class: 'image-prev-settings', style: "width: 200px; display: block;" %>
          <% end %>
          <%= image_tag '', class: 'image-prev-settings', style: "width: 200px; display: block;" %>
        </div>
      </div>
    </div>

    <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
      <div class="actions">
        <%= form.submit (sample.persisted? ? t('actions.save') : t('actions.create_and_continue')), name: "save", class: "btn btn-primary btn-sm", data: { disable_with: (sample.persisted? ? t('actions.saving.long') : t('actions.creating.long')) } %>
      </div>
    </div>
  <% end %>
</div>

<style type="text/css">
    input[type=file] {
        width: 100%;
        height: 100%;
        cursor: pointer;
        vertical-align: middle;
        padding-top: 9px;
    }
</style>

<script type="text/javascript" charset="utf-8">
    $(document).ready(function () {
        // $('input[type="file"]').attr('title', window.webkitURL ? ' ' : '');

        // alert('dd');

        // $('#button').click(function(){
        //     $("input[type='file']").trigger('click');
        // })
        //
        // $("input[type='file']").change(function(){
        //     $('#val').text(this.value.replace(/C:\\fakepath\\/i, ''))
        // })


        $(document).on('change', '.f-image-preview-input', function () {
            var row = $(this).parents('.col-md-6')
            // $(row[0].querySelector('.text-danger')).hide();

            var preview = row[0].querySelector('.image-prev-settings');
            var file = row[0].querySelector('.f-image-preview-input').files[0];
            var reader = new FileReader();

            reader.onloadend = function () {
                preview.src = reader.result;
            }

            if (file) {
                reader.readAsDataURL(file);
            } else {
                preview.src = "";
            }
        });

    });

</script>

app/views/samples/_index.html.erb
<%
  return_to ||= local_assigns.fetch(:return_to, request.fullpath)
  samples_scope_meta ||= nil
  samples ||= nil
%>

<div class="card mb-4">
  <%= render partial: "samples/index_toolbar", locals: {
      return_to: return_to,
      samples_scope_meta: samples_scope_meta,
      search_criteria: :title_or_sub_title_or_url_cont,
      search_url: samples_path,
      show_actions: false
  } %>

  <%= render partial: "samples/samples_table", locals: {
      return_to: return_to,
      samples_scope_meta: samples_scope_meta,
      samples: samples
  } %>

  <%= render partial: "samples/index_bottombar" %>
</div>

app/views/samples/_index_toolbar.html.erb
<%
  return_to ||= local_assigns.fetch(:return_to, request.fullpath)
  samples_scope_meta = local_assigns.fetch(:samples_scope_meta, nil)
  search_criteria = local_assigns.fetch(:search_criteria, nil)
  search_url = local_assigns.fetch(:search_url, nil)
%>

<div class="card-header">
  <%= link_to new_sample_path(return_to: return_to), class: "btn btn-success btn-sm", data: { toggle: 'tooltip', placement: 'top' }, title: t('actions.new') do %>
    <i class="fa fa-link fa-fw" aria-hidden="true"></i>
    <%= t('samples.new.button_title') %>
  <% end %>

  <div class="float-right">
    <%== pagy_bootstrap_combo_nav_js(@pagy) %>
  </div>


  <%= search_form_for samples_scope_meta, url: search_url, class: 'd-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0 float-right' do |f| %>
    <div class="input-group">
      <%= f.search_field search_criteria, class: 'form-control', autocomplete: "off", placeholder: "#{t('actions.search_for')}..." %>

      <div class="input-group-append">
        <%= button_tag type: 'submit', class: 'btn btn-primary' do %>
          <i class="fa fa-search"></i>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/samples/_sample_row.html.erb
<%
  return_to = local_assigns.fetch(:return_to, request.fullpath)
  sample = local_assigns.fetch(:sample)
%>

<tr>
  <td>
    <div class="nowrap">
      <%= link_to sample.title, sample_path(sample) %>
    </div>
  </td>

  <td>
    <div class="nowrap">
      <%= sample.sub_title %>
    </div>
  </td>

  <td>
    <div class="nowrap">
      <%= sample.url %>
    </div>
  </td>

  <td>
    <div class="nowrap">
      <%= if_applicable(sample.created_at.present? ? l(sample.created_at) : nil, titleize: false) %>
    </div>
  </td>

  <td class="nowrap">
    <%#= link_to download_sample_as_word_sample_path(sample), class: "btn btn-sm", download: sample.title, data: { toggle: 'tooltip', placement: 'top' }, title: t('actions.download') do %>
<!--      <i class="fa fa-download fa-fw" aria-hidden="true"></i>-->
    <%# end %>

    <%#= link_to clone_sample_path(sample), class: "btn btn-sm", data: { toggle: 'tooltip', placement: 'top' }, title: t('actions.clone') do %>
<!--      <i class="fa fa-clone fa-fw" aria-hidden="true"></i>-->
    <%# end %>

    <%= link_to edit_sample_path(sample, return_to: samples_path), class: "btn btn-sm", data: { toggle: 'tooltip', placement: 'top' }, title: t('actions.edit') do %>
      <i class="fa fa-pencil-alt fa-fw" aria-hidden="true"></i>
    <% end %>

    <%= link_to sample_path(sample), method: :delete, class: "btn btn-sm", data: { confirm: t("actions.confirm"), toggle: 'tooltip', placement: 'top', disable_with: t('actions.deleting.short') }, title: t('actions.delete') do %>
      <i class="fa fa-times fa-lg fa-fw" aria-hidden="true"></i>
    <% end %>
  </td>
</tr>

app/views/samples/_samples_table.html.erb
<%
  return_to = local_assigns.fetch(:return_to, request.fullpath)
  samples = local_assigns.fetch(:samples, [])
  samples_scope_meta ||= nil
  sample_model = Sample
%>

<div class="card-body">
  <div class="table-responsive">
    <table class="table table-bordered table-striped" id="dataTable" width="100%" cellspacing="0">
      <thead>
      <tr>
        <th>
          <%= sort_link(samples_scope_meta, :title, { default_order: :asc }) %>
        </th>

        <th>
          <%= sort_link(samples_scope_meta, :sub_title, { default_order: :asc }) %>
        </th>

        <th>
          <%= sort_link(samples_scope_meta, :url, { default_order: :asc }) %>
        </th>

        <th>
          <%= sort_link(samples_scope_meta, :created_at, { default_order: :asc }) %>
        </th>

        <th colspan="2"></th>
      </tr>
      </thead>

      <tbody>
      <% if samples.present? %>
        <%= render partial: "samples/sample_row", collection: samples, as: :sample, locals: { return_to: return_to } %>
      <% else %>
        <tr>
          <td colspan="6" class="text-center">
            <i class="fa fa-info-circle"></i>
            <i><%= t('errors.resources.not_found', resource: humanize_model(sample_model, pluralize: true, titleize: false)) %></i>
          </td>
        </tr>
      <% end %>
      </tbody>

    </table>
  </div>
</div>

app/views/samples/edit.html.erb
<%
  sample = @sample || Sample.new
  return_to = @return_to
%>

<br>
<h1 class="mt-4"><%= t('samples.update.header') %></h1>

<ol class="breadcrumb mb-4 hidden-print">
  <li>
    <%= link_to samples_path do %>
      <%= t('samples.nav') %>
    <% end %>
  </li> &nbsp;/&nbsp;
  <li class="active"> <%= t('samples.update.header') %></li>
</ol>

<div class="card mb-4">
  <div class="card-header">
    <%= link_to return_to, class: "btn btn-danger btn-sm", data: { toggle: 'tooltip', placement: 'top' }, title: t('actions.back') do %>
      <i class="fa fa-hand-point-left fa-fw" aria-hidden="true"></i>
      Back
    <% end %>
  </div>

  <%= render partial: 'form', locals: {
      sample: sample,
      return_to: return_to,
  } %>
</div>

app/views/samples/index.html.erb
<br>
<h1 class="mt-4"><%= t("samples.title") %></h1>

<ol class="breadcrumb mb-4 hidden-print">
  <li class="breadcrumb-item active"><%= t('samples.nav') %></li>
</ol>

<%= render partial: 'samples/index', locals: {
    return_to: samples_path,
    samples_scope_meta: @samples_scope_meta,
    samples: @samples
} %>

app/views/samples/new.html.erb
<%
  sample = @sample || Sample.new
  return_to = @return_to
%>

<br>
<h1 class="mt-4"><%= t('samples.new.header') %></h1>

<ol class="breadcrumb mb-4 hidden-print">
  <li>
    <%= link_to samples_path do %>
      <%= t('samples.nav') %>
    <% end %>
  </li> &nbsp;/&nbsp;
  <li class="active"> <%= t('samples.create.header') %></li>
</ol>

<div class="card mb-4">
  <div class="card-header">
    <%= link_to samples_path, class: "btn btn-danger btn-sm", data: { toggle: 'tooltip', placement: 'top' }, title: t('actions.back') do %>
      <i class="fa fa-hand-point-left fa-fw" aria-hidden="true"></i>
      Back
    <% end %>
  </div>

  <%= render partial: 'form', locals: {
      sample: sample,
      return_to: return_to,
  } %>
</div>

app/views/samples/show.html.erb
<br>
<h1 class="mt-4"><%= t("samples.details.header") %></h1>

<ol class="breadcrumb mb-4 hidden-print">
  <li>
    <%= link_to samples_path do %>
      <%= t('samples.nav') %>
    <% end %>
  </li> &nbsp;/&nbsp;
  <li class="active"> <%= t('samples.details.header') %></li>
</ol>

<div class="card mb-4">
  <div class="card-header">
    <%= link_to sample_path(@sample), method: :delete, class: "btn btn-danger btn-sm", data: { confirm: t("actions.confirm"), toggle: 'tooltip', placement: 'top', disable_with: t('actions.deleting.short') }, title: t('actions.delete') do %>
      <i class="fa fa-times fa-fw" aria-hidden="true"></i>
      Delete Sample
    <% end %>

    <%= link_to edit_sample_path(@sample, return_to: sample_path(@sample)), class: "btn btn-success btn-sm", data: { toggle: 'tooltip', placement: 'top' }, title: t('actions.edit') do %>
      <i class="fa fa-pencil-alt fa-fw" aria-hidden="true"></i>
      Edit Sample
    <% end %>
  </div>

  <div class="card-body">
    <!-- Details Row # 1:  -->
    <div class="form-row">
      <div class="col-md-6">
        <div class="form-group">
          <label class="small mb-1">
            Title:
          </label>
          <div class="form-control" style="height: 50px; vertical-align: middle !important; padding-top: 12px;">
            <%= if_applicable @sample.title, titleize: false %>
          </div>
        </div>
      </div>

      <div class="col-md-6">
        <div class="form-group">
          <label class="small mb-1">
            Sub title:
          </label>
          <div class="form-control" style="height: 50px; vertical-align: middle !important; padding-top: 12px;">
            <%= if_applicable @sample.sub_title, titleize: false %>
          </div>
        </div>
      </div>
    </div>

    <!-- Details Row # 2:  -->
    <div class="form-row">
      <div class="col-md-6">
        <div class="form-group">
          <label class="small mb-1">
            Url:
          </label>
          <div class="form-control" style="height: 50px; vertical-align: middle !important; padding-top: 12px;">
            <%= if_applicable @sample.url, titleize: false %>
          </div>
        </div>
      </div>

      <div class="col-md-6">
        <div class="form-group">
          <label class="small mb-1">
            Image:
          </label>
          <div class="form-control" style="height: 50px; vertical-align: middle !important; padding-top: 12px;">
            <%= if_applicable @sample.image.filename, titleize: false %>
          </div>
          <br>
          <% if @sample.image.attached? %>
            <%= image_tag @sample.image, style: "width: 200px; display: block;" %>
          <% end %>
        </div>
      </div>
    </div>

    <!-- Separation Row: Makes this partial more similar to the edit/new form  -->
    <div class="form-group"></div>

    <!-- Separation Row: Makes this partial more similar to the edit/new form  -->
    <div class="form-group"></div>
  </div>
</div>