config/routes.rb
Rails.application.routes.draw do

  # devise_for :users
  #
  # devise_for :users, controllers: {
  #   # confirmations: 'users/confirmations'
  #   confirmations: 'users/confirmations',
  #   registrations: 'users/registrations',
  #   sessions: 'users/sessions'
  # }


  # devise_for :users, skip: [:registrations]
  devise_for :users, skip: [:registrations], controllers: {
    # confirmations: 'users/confirmations'
    confirmations: 'users/confirmations',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  as :user do
    # get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    # put 'users' => 'devise/registrations#update', :as => 'user_registration'

    get 'users/edit' => 'users/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'users/registrations#update', :as => 'user_registration'
  end

  resources :contacts do
    get :block_contact, on: :member
    get :unblock_contact, on: :member
  end
  resources :skills
  resources :references
  resources :samples

  # Royal Ciinema
  resources :auditoriums

  # The extra_pages view (extra)
  get 'pages', to: 'pages#index'

  # root :to => redirect("/pages")
  root to: redirect("pages")
end

app/models/skill.rb
# frozen_string_literal: true

class Skill < ApplicationRecord

  # Validations:
  validates :name, presence: true
  validates :name, uniqueness: true
  validates :color, presence: true
  validates :percentage, presence: true
  validates :percentage, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 100 }

end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  include CommonControl

  before_action :authenticate_user!
  before_action :set_skill, only: %i[show edit update destroy]
  before_action :update_concerned_path, only: [:new, :create, :edit, :update]

  def index
    skills_scope = Skill.all
    @skills_scope_meta = skills_scope.ransack(@scope)
    @skills_scope_meta.sorts = "#{@sort_column} #{@sort_direction}" if @skills_scope_meta.sorts.empty?
    @pagy, @skills = pagy(@skills_scope_meta.result, items: 10)
  end

  def show; end

  def new
    @skill = Skill.new
  end

  def edit
  end

  def create
    @skill = skill_service.build_skill(skill_params)

    if @skill.save
      redirect_notice = t('skills.create.success_notice')
      redirect_to @return_to, notice: redirect_notice
    else
      flash[:alert] = @skill.errors.full_messages.first
      render :new
    end
  end

  def update
    @skill = skill_service.update_skill(skill_params.merge(id: params.fetch(:id)))

    if @skill.save
      redirect_notice = t('skills.update.success_notice')
      redirect_to @return_to, notice: redirect_notice
    else
      flash[:alert] = @skill.errors.full_messages.first
      render action: :edit
    end
  end

  def destroy
    @skill.destroy
    respond_to do |format|
      format.html { redirect_to skills_url, notice: t('skills.destroy.success_notice') }
      format.json { head :no_content }
    end
  end

  private

  def skill_service
    SkillService
  end

  def set_skill
    @skill = Skill.all.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def skill_params
    params.fetch(:skill, {}).permit(:name, :color, :percentage)
  end

end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/skills/_contact_row.html.erb
<%
  return_to = local_assigns.fetch(:return_to, request.fullpath)
  contact = local_assigns.fetch(:contact)
  body_truncate_length = 160
  # body_text = text_from_note(contact)
  body_text = contact.message
%>

<tr>
  <td>
    <div class="nowrap">
      <%= link_to contact.name, contact_path(contact) %>
    </div>
  </td>

  <td>
    <div class="nowrap">
      <%= contact.email %>
    </div>
  </td>

  <td>
    <div class="nowrap">
      <%= contact.subject %>
    </div>
  </td>

  <td>
    <div class="nowrap">
      <% popover_data = body_text.length > body_truncate_length ? { toggle: :popover, trigger: :hover, title: t('contacts.column_header_labels.body'), content: contact.message.to_s, placement: :left, html: true } : {} %>
      <%= content_tag :div, data: popover_data do %>
        <%= truncate(body_text, length: body_truncate_length) %>
      <% end %>
    </div>
  </td>

  <td>
    <div class="nowrap">
      <%= if_applicable(contact.created_at.present? ? l(contact.created_at) : nil, titleize: false) %>
    </div>
  </td>

  <td class="nowrap">
    <%#= link_to download_contact_as_word_contact_path(contact), class: "btn btn-sm", download: note.title, data: { toggle: 'tooltip', placement: 'top' }, title: t('actions.download') do %>
    <!--      <i class="fa fa-download fa-fw" aria-hidden="true"></i>-->
    <%# end %>

    <%#= link_to clone_contact_path(contact), class: "btn btn-sm", data: { toggle: 'tooltip', placement: 'top' }, title: t('actions.clone') do %>
    <!--      <i class="fa fa-clone fa-fw" aria-hidden="true"></i>-->
    <%# end %>

    <%#= link_to edit_contact_path(contact, return_to: contacts_path), class: "btn btn-sm", data: { toggle: 'tooltip', placement: 'top' }, title: t('actions.edit') do %>
    <!--      <i class="fa fa-pencil-alt fa-fw" aria-hidden="true"></i>-->
    <%# end %>

    <%= link_to contact_path(contact), method: :delete, class: "btn btn-sm", data: { confirm: t("actions.confirm"), toggle: 'tooltip', placement: 'top', disable_with: t('actions.deleting.short') }, title: t('actions.delete') do %>
      <i class="fa fa-times fa-lg fa-fw" aria-hidden="true"></i>
    <% end %>
  </td>
</tr>

app/views/skills/_contacts_table.html.erb
<%
  return_to = local_assigns.fetch(:return_to, request.fullpath)
  contacts = local_assigns.fetch(:contacts, [])
  contacts_scope_meta ||= nil
  contact_model = Contact
%>

<div class="card-body">
  <div class="table-responsive">
    <table class="table table-bordered table-striped" id="dataTable" width="100%" cellspacing="0">
      <thead>
      <tr>
        <th>
          <%= sort_link(contacts_scope_meta, :name, { default_order: :asc }) %>
        </th>

        <th>
          <%= sort_link(contacts_scope_meta, :email, { default_order: :asc }) %>
        </th>

        <th>
          <%= sort_link(contacts_scope_meta, :subject, { default_order: :asc }) %>
        </th>

        <th>
          <%= sort_link(contacts_scope_meta, :message, { default_order: :asc }) %>
        </th>

        <th>
          <%= sort_link(contacts_scope_meta, :created_at, { default_order: :asc }) %>
        </th>

        <th colspan="1"></th>
      </tr>
      </thead>

      <tbody>
      <% if contacts.present? %>
        <%= render partial: "contacts/contact_row", collection: contacts, as: :contact, locals: { return_to: return_to } %>
      <% else %>
        <tr>
          <td colspan="6" class="text-center">
            <i class="fa fa-info-circle"></i>
            <i><%= t('errors.resources.not_found', resource: humanize_model(contact_model, pluralize: true, titleize: false)) %></i>
          </td>
        </tr>
      <% end %>
      </tbody>

    </table>
  </div>
</div>

app/views/skills/_form.html.erb
<%
  skill_model = Skill
  skill = local_assigns.fetch(:skill, Skill.new)
  return_to = local_assigns.fetch(:return_to, request.fullpath)
  color_value = (skill.persisted? ? skill.color : "##{SecureRandom.hex(3)}")
%>

<div class="card-body">
  <%= form_with(model: skill, local: true) do |form| %>
    <%= hidden_field_tag :return_to, return_to %>

    <div class="form-row">
      <div class="col-md-6">
        <div class="form-group">
          <%= form.label :name, humanize_attribute(skill_model, :name), class: 'small mb-1' %>
          <%= form.text_field :name, class: 'form-control py-4', autofocus: true, autocomplete: "name", placeholder: 'Enter the name' %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <%= form.label :color, humanize_attribute(skill_model, :color), class: 'small mb-1' %>
          <%= form.color_field :color, value: color_value, style: "width: 100%; height: 50px;", input_html: { class: 'colorpicker' } %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :percentage, humanize_attribute(skill_model, :percentage), class: 'small mb-1' %>
      <%= form.text_field :percentage, class: 'form-control py-4', autofocus: true, autocomplete: "title", placeholder: 'Enter the percentage' %>
    </div>

    <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
      <div class="actions">
        <%= form.submit (skill.persisted? ? t('actions.save') : t('actions.create_and_continue')), name: "save", class: "btn btn-primary btn-sm", data: { disable_with: (skill.persisted? ? t('actions.saving.long') : t('actions.creating.long')) } %>
      </div>
    </div>
  <% end %>
</div>

app/views/skills/_index.html.erb
<%
  return_to ||= local_assigns.fetch(:return_to, request.fullpath)
  skills_scope_meta ||= nil
  skills ||= nil
%>

<div class="card mb-4">
  <%= render partial: "skills/index_toolbar", locals: {
      return_to: return_to,
      skills_scope_meta: skills_scope_meta,
      search_criteria: :name_cont,
      search_url: skills_path,
      show_actions: false
  } %>

  <%= render partial: "skills/skills_table", locals: {
      return_to: return_to,
      skills_scope_meta: skills_scope_meta,
      skills: skills
  } %>

  <%= render partial: "skills/index_bottombar" %>
</div>

app/views/skills/_index_toolbar.html.erb
<%
  return_to ||= local_assigns.fetch(:return_to, request.fullpath)
  skills_scope_meta = local_assigns.fetch(:skills_scope_meta, nil)
  search_criteria = local_assigns.fetch(:search_criteria, nil)
  search_url = local_assigns.fetch(:search_url, nil)
%>

<div class="card-header">
  <%= link_to new_skill_path(return_to: return_to), class: "btn btn-success btn-sm", data: { toggle: 'tooltip', placement: 'top' }, title: t('actions.new') do %>
    <i class="fa fa-cogs fa-fw" aria-hidden="true"></i>
    <%= t('skills.new.button_title') %>
  <% end %>

  <div class="float-right">
    <%== pagy_bootstrap_combo_nav_js(@pagy) %>
  </div>


  <%= search_form_for skills_scope_meta, url: search_url, class: 'd-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0 float-right' do |f| %>
    <div class="input-group">
      <%= f.search_field search_criteria, class: 'form-control', autocomplete: "off", placeholder: "#{t('actions.search_for')}..." %>

      <div class="input-group-append">
        <%= button_tag type: 'submit', class: 'btn btn-primary' do %>
          <i class="fa fa-search"></i>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/skills/_skill_row.html.erb
<%
  return_to = local_assigns.fetch(:return_to, request.fullpath)
  skill = local_assigns.fetch(:skill)
%>

<tr>
  <td>
    <div class="nowrap">
      <%= link_to skill.name, skill_path(skill) %>
    </div>
  </td>

  <td>
    <%= content_tag(:div, skill.color, class: "badge", style: "color: white; background: #{skill.color};") %>
  </td>

  <td>
    <div class="nowrap">
      <%= skill.percentage %>
    </div>
  </td>

  <td>
    <div class="nowrap">
      <%= if_applicable(skill.created_at.present? ? l(skill.created_at) : nil, titleize: false) %>
    </div>
  </td>

  <td class="nowrap">
    <%#= link_to download_skill_as_word_skill_path(skill), class: "btn btn-sm", download: note.title, data: { toggle: 'tooltip', placement: 'top' }, title: t('actions.download') do %>
    <!--      <i class="fa fa-download fa-fw" aria-hidden="true"></i>-->
    <%# end %>

    <%#= link_to clone_skill_path(skill), class: "btn btn-sm", data: { toggle: 'tooltip', placement: 'top' }, title: t('actions.clone') do %>
    <!--      <i class="fa fa-clone fa-fw" aria-hidden="true"></i>-->
    <%# end %>

    <%= link_to edit_skill_path(skill, return_to: skills_path), class: "btn btn-sm", data: { toggle: 'tooltip', placement: 'top' }, title: t('actions.edit') do %>
      <i class="fa fa-pencil-alt fa-fw" aria-hidden="true"></i>
    <% end %>

    <%= link_to skill_path(skill), method: :delete, class: "btn btn-sm", data: { confirm: t("actions.confirm"), toggle: 'tooltip', placement: 'top', disable_with: t('actions.deleting.short') }, title: t('actions.delete') do %>
      <i class="fa fa-times fa-lg fa-fw" aria-hidden="true"></i>
    <% end %>
  </td>
</tr>

app/views/skills/_skills_table.html.erb
<%
  return_to = local_assigns.fetch(:return_to, request.fullpath)
  skills = local_assigns.fetch(:skills, [])
  skills_scope_meta ||= nil
  skill_model = Skill
%>

<div class="card-body">
  <div class="table-responsive">
    <table class="table table-bordered table-striped" id="dataTable" width="100%" cellspacing="0">
      <thead>
      <tr>
        <th>
          <%= sort_link(skills_scope_meta, :name, { default_order: :asc }) %>
        </th>

        <th>
          <%= sort_link(skills_scope_meta, :color, { default_order: :asc }) %>
        </th>

        <th>
          <%= sort_link(skills_scope_meta, :percentage, { default_order: :desc }) %>
        </th>

        <th>
          <%= sort_link(skills_scope_meta, :created_at, { default_order: :asc }) %>
        </th>

        <th colspan="2"></th>
      </tr>
      </thead>

      <tbody>
      <% if skills.present? %>
        <%= render partial: "skills/skill_row", collection: skills, as: :skill, locals: { return_to: return_to } %>
      <% else %>
        <tr>
          <td colspan="6" class="text-center">
            <i class="fa fa-info-circle"></i>
            <i><%= t('errors.resources.not_found', resource: humanize_model(skill_model, pluralize: true, titleize: false)) %></i>
          </td>
        </tr>
      <% end %>
      </tbody>

    </table>
  </div>
</div>

app/views/skills/edit.html.erb
<%
  skill = @skill || Skill.new
  return_to = @return_to
%>

<br>
<h1 class="mt-4"><%= t('skills.update.header') %></h1>

<ol class="breadcrumb mb-4 hidden-print">
  <li>
    <%= link_to skills_path do %>
      <%= t('skills.nav') %>
    <% end %>
  </li> &nbsp;/&nbsp;
  <li class="active"> <%= t('skills.update.header') %></li>
</ol>

<div class="card mb-4">
  <div class="card-header">
    <%= link_to return_to, class: "btn btn-danger btn-sm", data: { toggle: 'tooltip', placement: 'top' }, title: t('actions.back') do %>
      <i class="fa fa-hand-point-left fa-fw" aria-hidden="true"></i>
      Back
    <% end %>
  </div>

  <%= render partial: 'form', locals: {
    skill: skill,
    return_to: return_to,
  } %>
</div>

app/views/skills/index.html.erb
<br>
<h1 class="mt-4"><%= t("skills.title") %></h1>

<ol class="breadcrumb mb-4 hidden-print">
  <li class="breadcrumb-item active"><%= t('skills.nav') %></li>
</ol>

<%= render partial: 'skills/index', locals: {
    return_to: skills_path,
    skills_scope_meta: @skills_scope_meta,
    skills: @skills
} %>

app/views/skills/new.html.erb
<%
  skill = @skill || Skill.new
  return_to = @return_to
%>

<br>
<h1 class="mt-4"><%= t('skills.new.header') %></h1>

<ol class="breadcrumb mb-4 hidden-print">
  <li>
    <%= link_to skills_path do %>
      <%= t('skills.nav') %>
    <% end %>
  </li> &nbsp;/&nbsp;
  <li class="active"> <%= t('skills.create.header') %></li>
</ol>

<div class="card mb-4">
  <div class="card-header">
    <%= link_to skills_path, class: "btn btn-danger btn-sm", data: { toggle: 'tooltip', placement: 'top' }, title: t('actions.back') do %>
      <i class="fa fa-hand-point-left fa-fw" aria-hidden="true"></i>
      Back
    <% end %>
  </div>

  <%= render partial: 'form', locals: {
    skill: skill,
    return_to: return_to,
  } %>
</div>

app/views/skills/show.html.erb
<br>
<h1 class="mt-4"><%= t("skills.details.header") %></h1>

<ol class="breadcrumb mb-4 hidden-print">
  <li>
    <%= link_to skills_path do %>
      <%= t('skills.nav') %>
    <% end %>
  </li> &nbsp;/&nbsp;
  <li class="active"> <%= t('skills.details.header') %></li>
</ol>

<div class="card mb-4">
  <div class="card-header">
    <%= link_to skill_path(@skill), method: :delete, class: "btn btn-danger btn-sm", data: { confirm: t("actions.confirm"), toggle: 'tooltip', placement: 'top', disable_with: t('actions.deleting.short') }, title: t('actions.delete') do %>
      <i class="fa fa-times fa-fw" aria-hidden="true"></i>
      Delete Skill
    <% end %>

    <%= link_to edit_skill_path(@skill, return_to: skill_path(@skill)), class: "btn btn-success btn-sm", data: { toggle: 'tooltip', placement: 'top' }, title: t('actions.edit') do %>
      <i class="fa fa-pencil-alt fa-fw" aria-hidden="true"></i>
      Edit Skill
    <% end %>
  </div>

  <div class="card-body">
    <!-- Details Row # 1:  -->
    <div class="form-row">
      <div class="col-md-6">
        <div class="form-group">
          <label class="small mb-1">
            Name:
          </label>
          <div class="form-control" style="height: 50px; vertical-align: middle !important; padding-top: 12px;">
            <%= if_applicable @skill.name, titleize: false %>
          </div>
        </div>
      </div>

      <div class="col-md-6">
        <div class="form-group">
          <label class="small mb-1">
            Color:
          </label>
          <div class="form-control" style="color: white; background: <%= @skill.color %>; height: 50px; vertical-align: middle !important; padding-top: 12px;">
            <%= if_applicable @skill.color, titleize: false %>
          </div>
        </div>
      </div>
    </div>

    <!-- Details Row # 2:  -->
    <div class="form-row">
      <div class="col-md-12">
        <div class="form-group">
          <label class="small mb-1">
            Percentage:
          </label>
          <div class="form-control" style="height: 50px; vertical-align: middle !important; padding-top: 12px;">
            <%= if_applicable @skill.percentage, titleize: false %>
          </div>
        </div>
      </div>
    </div>

    <!-- Separation Row: Makes this partial more similar to the edit/new form  -->
    <div class="form-group"></div>

    <!-- Separation Row: Makes this partial more similar to the edit/new form  -->
    <div class="form-group"></div>
  </div>
</div>