config/routes.rb
Rails.application.routes.draw do

  # devise_for :users
  #
  # devise_for :users, controllers: {
  #   # confirmations: 'users/confirmations'
  #   confirmations: 'users/confirmations',
  #   registrations: 'users/registrations',
  #   sessions: 'users/sessions'
  # }


  # devise_for :users, skip: [:registrations]
  devise_for :users, skip: [:registrations], controllers: {
    # confirmations: 'users/confirmations'
    confirmations: 'users/confirmations',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  as :user do
    # get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    # put 'users' => 'devise/registrations#update', :as => 'user_registration'

    get 'users/edit' => 'users/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'users/registrations#update', :as => 'user_registration'
  end

  resources :contacts do
    get :block_contact, on: :member
    get :unblock_contact, on: :member
  end
  resources :skills
  resources :references
  resources :samples

  # Royal Ciinema
  resources :auditoriums

  # The extra_pages view (extra)
  get 'pages', to: 'pages#index'

  # root :to => redirect("/pages")
  root to: redirect("pages")
end

app/models/contact.rb
class Contact < ApplicationRecord

  require 'obscenity/active_model'

  # Validations:
  validates :name, presence: true

  validates :email, presence: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
  validate :email_is_not_blacklisted

  validates :subject, presence: true
  validates :subject, obscenity: true

  validates :message, presence: true
  validates :message, obscenity: true

  def email_blacklisted?
    BlackList.find_by_black_list_type_and_value("email", self.email).present?
  end

  private

  def email_is_not_blacklisted
    if BlackList.find_by_black_list_type_and_value("email", self.email)
      errors.add(:email, 'is blacklisted')
    end
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  include CommonControl

  before_action :authenticate_user!, only: %i[index show destroy]
  before_action :set_contact, only: %i[show destroy block_contact unblock_contact]
  before_action :update_concerned_path, only: [:create]

  def index
    contacts_scope = Contact.all
    @contacts_scope_meta = contacts_scope.ransack(@scope)
    @contacts_scope_meta.sorts = "#{@sort_column} #{@sort_direction}" if @contacts_scope_meta.sorts.empty?
    @pagy, @contacts = pagy(@contacts_scope_meta.result, items: 10)
  end

  def show; end

  def create
    @contact = contact_service.build_contact(contact_params)
    # response = contact_service.send_email(@contact)
    # status_notice = if response.status_code.to_i == 202
    #                   ' & was sent successfully'
    #                 else
    #                   ' & was not sent successfully'
    #                 end

    if verify_recaptcha(model: @contact) && @contact.save
      redirect_notice = t('contacts.send.success_notice')
      redirect_to @return_to, notice: redirect_notice
    else
      flash[:alert] = @contact.errors.full_messages.first
      # redirect_notice = 'Your message was not sent.'
      # redirect_to @return_to, alert: redirect_notice
      redirect_to @return_to
    end
  end

  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: t('contacts.destroy.success_notice') }
      format.json { head :no_content }
    end
  end

  def block_contact
    contact_service.block_contact(@contact)
    redirect_to contacts_url, notice: t('contacts.block.success_notice')
  end

  def unblock_contact
    contact_service.unblock_contact(@contact)
    redirect_to contacts_url, notice: t('contacts.unblock.success_notice')
  end

  private

  def contact_service
    ContactService
  end

  def set_contact
    @contact = Contact.all.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def contact_params
    params.fetch(:contact, {}).permit(:name, :email, :subject, :message)
  end

end

app/helpers/contacts_helper.rb
module ContactsHelper
  extend self

  # Display value if applicable
  def if_applicable(value, titleize: true, not_applicable: t('messages.not_applicable'), attribute: nil)

    # Return not applicable if there is no value
    unless value.present?
      return not_applicable
    end

    # Replace value for an attribute of a given object
    if attribute.present?
      value = value.send(attribute)
    end

    # Apply options
    if titleize
      value = value.to_s.titleize
    end

    # Return the enhanced value
    value
  end

end

app/views/contacts/_contact_row.html.erb
<%
  return_to = local_assigns.fetch(:return_to, request.fullpath)
  contact = local_assigns.fetch(:contact)
  subject_truncate_length = 34
  message_truncate_length = 60
  body_text = contact.message
  class_by_validity = contact.email_blacklisted? ? 'bg-warning' : ''
%>

<tr class="<%= class_by_validity %>">
  <td>
    <div class="nowrap">
      <%= link_to contact.name, contact_path(contact) %>
    </div>
  </td>

  <td>
    <div class="nowrap">
      <%= contact.email %>
    </div>
  </td>

  <td>
    <div class="nowrap">
      <%= truncate(body_text, length: subject_truncate_length) %>
    </div>
  </td>

  <td>
    <div class="nowrap">
      <% popover_data = body_text.length > message_truncate_length ? { toggle: :popover, trigger: :hover, title: t('contacts.column_header_labels.body'), content: contact.message.to_s, placement: :left, html: true } : {} %>
      <%= content_tag :div, data: popover_data do %>
        <%= truncate(body_text, length: message_truncate_length) %>
      <% end %>
    </div>
  </td>

  <td>
    <div class="nowrap">
      <%= if_applicable(contact.created_at.present? ? l(contact.created_at) : nil, titleize: false) %>
    </div>
  </td>

  <td class="nowrap">
    <%#= link_to download_contact_as_word_contact_path(contact), class: "btn btn-sm", download: note.title, data: { toggle: 'tooltip', placement: 'top' }, title: t('actions.download') do %>
    <!--      <i class="fa fa-download fa-fw" aria-hidden="true"></i>-->
    <%# end %>

    <%#= link_to clone_contact_path(contact), class: "btn btn-sm", data: { toggle: 'tooltip', placement: 'top' }, title: t('actions.clone') do %>
    <!--      <i class="fa fa-clone fa-fw" aria-hidden="true"></i>-->
    <%# end %>

    <%#= link_to edit_contact_path(contact, return_to: contacts_path), class: "btn btn-sm", data: { toggle: 'tooltip', placement: 'top' }, title: t('actions.edit') do %>
    <!--      <i class="fa fa-pencil-alt fa-fw" aria-hidden="true"></i>-->
    <%# end %>

    <% if contact.email_blacklisted? %>
      <%= link_to unblock_contact_contact_path(contact), class: "btn btn-sm", data: { toggle: 'tooltip', placement: 'top', disable_with: t('actions.unblocking.short') }, title: t('actions.unblock') do %>
        <i class="fa fa-check fa-fw" aria-hidden="true"></i>
      <% end %>
    <% else %>
      <%= link_to block_contact_contact_path(contact), class: "btn btn-sm", data: { confirm: t("actions.confirm"), toggle: 'tooltip', placement: 'top', disable_with: t('actions.blocking.short') }, title: t('actions.block') do %>
        <i class="fa fa-ban fa-fw" aria-hidden="true"></i>
      <% end %>
    <% end %>

    <%= link_to contact_path(contact), method: :delete, class: "btn btn-sm", data: { confirm: t("actions.confirm"), toggle: 'tooltip', placement: 'top', disable_with: t('actions.deleting.short') }, title: t('actions.delete') do %>
      <i class="fa fa-times fa-lg fa-fw" aria-hidden="true"></i>
    <% end %>
  </td>
</tr>

app/views/contacts/_contacts_table.html.erb
<%
  return_to = local_assigns.fetch(:return_to, request.fullpath)
  contacts = local_assigns.fetch(:contacts, [])
  contacts_scope_meta ||= nil
  contact_model = Contact
%>

<div class="card-body">
  <div class="table-responsive">
    <table class="table table-bordered table-striped" id="dataTable" width="100%" cellspacing="0">
      <thead>
      <tr>
        <th>
          <%= sort_link(contacts_scope_meta, :name, { default_order: :asc }) %>
        </th>

        <th>
          <%= sort_link(contacts_scope_meta, :email, { default_order: :asc }) %>
        </th>

        <th>
          <%= sort_link(contacts_scope_meta, :subject, { default_order: :asc }) %>
        </th>

        <th>
          <%= sort_link(contacts_scope_meta, :message, { default_order: :asc }) %>
        </th>

        <th>
          <%= sort_link(contacts_scope_meta, :created_at, { default_order: :asc }) %>
        </th>

        <th colspan="2"></th>
      </tr>
      </thead>

      <tbody>
      <% if contacts.present? %>
        <%= render partial: "contacts/contact_row", collection: contacts, as: :contact, locals: { return_to: return_to } %>
      <% else %>
        <tr>
          <td colspan="7" class="text-center">
            <i class="fa fa-info-circle"></i>
            <i><%= t('errors.resources.not_found', resource: humanize_model(contact_model, pluralize: true, titleize: false)) %></i>
          </td>
        </tr>
      <% end %>
      </tbody>

    </table>
  </div>
</div>

app/views/contacts/_index_toolbar.html.erb
<%
  return_to ||= local_assigns.fetch(:return_to, request.fullpath)
  contacts_scope_meta = local_assigns.fetch(:contacts_scope_meta, nil)
  search_criteria = local_assigns.fetch(:search_criteria, nil)
  search_url = local_assigns.fetch(:search_url, nil)
%>

<div class="card-header">
  <%= link_to new_contact_path, class: "btn btn-success btn-sm", data: { toggle: 'tooltip', placement: 'top' }, title: t('actions.new') do %>
    <i class="fa fa-paper-plane fa-fw" aria-hidden="true"></i>
    <%= t('contacts.new.button_title') %>
  <% end %>

  <div class="float-right">
    <%== pagy_bootstrap_combo_nav_js(@pagy) %>
  </div>


  <%= search_form_for contacts_scope_meta, url: search_url, class: 'd-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0 float-right' do |f| %>
    <div class="input-group">
      <%= f.search_field search_criteria, class: 'form-control', autocomplete: "off", placeholder: "#{t('actions.search_for')}..." %>

      <div class="input-group-append">
        <%= button_tag type: 'submit', class: 'btn btn-primary' do %>
          <i class="fa fa-search"></i>
        <% end %>
      </div>
    </div>
  <% end %>
</div>