config/routes.rb
Rails.application.routes.draw do

  # devise_for :users
  #
  # devise_for :users, controllers: {
  #   # confirmations: 'users/confirmations'
  #   confirmations: 'users/confirmations',
  #   registrations: 'users/registrations',
  #   sessions: 'users/sessions'
  # }


  # devise_for :users, skip: [:registrations]
  devise_for :users, skip: [:registrations], controllers: {
    # confirmations: 'users/confirmations'
    confirmations: 'users/confirmations',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  as :user do
    # get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    # put 'users' => 'devise/registrations#update', :as => 'user_registration'

    get 'users/edit' => 'users/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'users/registrations#update', :as => 'user_registration'
  end

  resources :contacts do
    get :block_contact, on: :member
    get :unblock_contact, on: :member
  end
  resources :skills
  resources :references
  resources :samples

  # Royal Ciinema
  resources :auditoriums

  # The extra_pages view (extra)
  get 'pages', to: 'pages#index'

  # root :to => redirect("/pages")
  root to: redirect("pages")
end

app/views/layouts/admin_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reinier Garcia: Ruby on Rails Developer</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta property="og:image" content="<%= asset_path 'reymillenium_logo_1024x1024.png' %>"/>
  <link rel="shortcut icon" href="<%= asset_path 'ruby-on-rails-logo.png' %>"/>

  <%= stylesheet_link_tag 'admin_layout' %>
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body class="sb-nav-fixed">

<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
  <img class="ml-4" style="width: 41px; height: 43px;" src=<%= "#{asset_path 'ruby-on-rails-logo.png'}" %>>
  <%= link_to contacts_path, class: 'navbar-brand' do %>
    <span style="color: #0369D9; font-weight: bold; font-family: 'Luminari' !important;">Rey</span><span style="color: #bc3939; font-weight: bold; font-family: 'Luminari' !important;">Millenium</span>
  <% end %>
  <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i>
  </button>
  <div class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
  </div>
  <!-- Navbar-->
  <ul class="navbar-nav ml-auto ml-md-0">
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
        <% if user_signed_in? %>
          <%= link_to 'Edit profile', edit_user_registration_path, class: 'dropdown-item' %>
          <div class="dropdown-divider"></div>
          <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path, class: 'dropdown-item' %>
          <%= link_to "Login", new_user_session_path, class: 'dropdown-item' %>
        <% end %>
      </div>
    </li>
  </ul>
</nav>
<div id="layoutSidenav">
  <div id="layoutSidenav_nav">
    <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
      <div class="sb-sidenav-menu">
        <div class="nav">
          <div class="sb-sidenav-menu-heading">Public</div>
          <%= link_to pages_path, class: 'nav-link' do %>
            <div class="sb-nav-link-icon"><i class="fas fa-briefcase"></i></div>
            Portfolio
          <% end %>

          <div class="sb-sidenav-menu-heading">Dashboard</div>
          <%= link_to contacts_path, class: 'nav-link' do %>
            <div class="sb-nav-link-icon"><i class="fas fa-paper-plane"></i></div>
            Messages
          <% end %>

          <%= link_to references_path, class: 'nav-link' do %>
            <div class="sb-nav-link-icon"><i class="fas fa-envelope"></i></div>
            References
          <% end %>

          <%= link_to skills_path, class: 'nav-link' do %>
            <div class="sb-nav-link-icon"><i class="fas fa-cogs"></i></div>
            Skills
          <% end %>

          <%= link_to samples_path, class: 'nav-link' do %>
            <div class="sb-nav-link-icon"><i class="fas fa-link"></i></div>
            Samples
          <% end %>

          <%= link_to auditoriums_path, class: 'nav-link' do %>
            <div class="sb-nav-link-icon"><i class="fas fa-photo-video"></i></div>
            <%= t("auditoriums.title") %>
          <% end %>
        </div>
      </div>
      <div class="sb-sidenav-footer">
        <div class="small">Logged in as:</div>
        <% if user_signed_in? %>
          <div><%= current_user.email %></div>
        <% else %>
          Start Bootstrap
        <% end %>
      </div>
    </nav>
  </div>
  <div id="layoutSidenav_content">
    <main>
      <div class="container-fluid">
        <%= render("shared/flash_messages") %>
        <%= yield %>
      </div>
    </main>

    <footer class="py-4 bg-light mt-auto">
      <div class="container-fluid">
        <div class="d-flex align-items-center justify-content-between small">
          <div class="text-muted">&copy; <%= Time.now.year.to_s %>. All rights reserved | Developed by
            <%= link_to "https://www.linkedin.com/in/reymillenium/", class: "linkedin", target: '_linkedin' do %>
              Reinier Garcia
            <% end %>
          </div>
          <div>
            <a href="#">Privacy Policy</a>
            &middot;
            <a href="#">Terms &amp; Conditions</a>
          </div>
        </div>
      </div>
    </footer>
  </div>
</div>
<!--<script src="app/javascript/packs/contacts/demo/chart-area-demo.js"></script>-->
<!--<script src="app/javascript/packs/contacts/demo/chart-bar-demo.js"></script>-->
<!--<script src="app/javascript/packs/contacts/demo/chart-pie-demo.js"></script>-->
<!--<script src="app/javascript/packs/contacts/demo/datatables-demo.js"></script>-->
<%= javascript_pack_tag 'contacts/scripts' %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reinier Garcia: Ruby on Rails Developer</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta property="og:image" content="<%= asset_path 'reymillenium_logo_1024x1024.png' %>"/>
  <link rel="shortcut icon" href="<%= asset_path 'ruby-on-rails-logo.png' %>"/>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<!-- banner -->
<div id="home" class="banner">
  <div class="banner-agileinfo">
    <!-- header -->
    <div class="header">
      <div class="container">
        <div class="logo">
          <!-- <h1><a href="index.html">Meet the Developer</a></h1>-->
          <%= link_to "users/sign_in", style: 'text-decoration: none; display: inline-block' do %>
            <h3 class="text-center font-weight-light my-4">
              <img class="ml-4" style="width: 41px; height: 43px;" src=<%= "#{asset_path 'ruby-on-rails-logo.png'}" %>>
              <span style="color: #0369D9; font-weight: bold; font-family: 'Luminari' !important;">Rey</span><span style="color: #bc3939; font-weight: bold; font-family: 'Luminari' !important;">Millenium</span>
            </h3>
          <% end %>
        </div>
        <div class="menu">
          <a href="" id="menuToggle"> <span class="navClosed"></span> </a>
          <nav id="sideBarNav">
            <a href="#home" class="active scroll">Home</a>
            <a href="#about" class="scroll">About Me</a>
            <a href="#skills" class="scroll">My Skills</a>
            <a href="#services" class="scroll">My Services</a>
            <a href="#interests" class="scroll">Interests</a>
            <a href="#experience" class="scroll">Experience</a>
            <a href="#education" class="scroll">My Education</a>
            <a href="#projects" class="scroll">My Projects</a>
            <a href="#references" class="scroll">References</a>
            <a href="#samples" class="scroll">Samples</a>
            <a href="#contact" class="scroll">Contact Me</a>
          </nav>
        </div>
        <div class="clearfix"></div>
      </div>
    </div>
    <!-- //header -->

    <%= render("shared/flash_messages") %>

    <div class="banner-main">
      <div class="container">
        <div class="col-md-5 banner-left">
          <img class="float-left" src=<%= "#{asset_path 'banner_reinier_portrait.png'}" %> alt="">
        </div>
        <div class="col-md-7 banner-text">
          <p>Welcome</p>
          <h2><span>I'm Reinier Garcia</span>Ruby on Rails Developer</h2>
          <div class="w3agile_hire_right">
            <a href="#contact" class="wthree-more w3more1 nina scroll" data-text="hire me">
              <span>h</span><span>i</span><span>r</span><span>e</span> <span>m</span><span>e</span>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- //banner -->

<%= yield %>

<!-- footer -->
<div class="footer w3ls">
  <div class="container">
    <div class="w3ls-social-icons-2">
      <%= link_to "https://www.linkedin.com/in/reymillenium/", class: "linkedin", target: '_linkedin' do %>
        <i class="fab fa-linkedin"></i>
      <% end %>

      <%= link_to "https://github.com/reymillenium/", class: "github", target: '_github' do %>
        <i class="fa fa-github"></i>
      <% end %>

      <%= link_to "https://stackoverflow.com/users/9616949/reinier-garcia?tab=profile", class: "stack-overflow", target: '_stack' do %>
        <i class="fab fa-stack-overflow"></i>
      <% end %>
    </div>
  </div>
</div>
<div class="copyrights">
  <p>&copy; <%= Time.now.year.to_s %>. All rights reserved | Developed by
    <%= link_to "https://www.linkedin.com/in/reymillenium/", class: "linkedin", target: '_linkedin' do %>
      Reinier Garcia
    <% end %>
  </p>
</div>
<!-- //footer -->

<!-- js-scripts -->
<script type="text/javascript">
    $(document).ready(function ($) {
        $(".scroll").click(function (event) {
            event.preventDefault();
            $('html,body').animate({scrollTop: $(this.hash).offset().top}, 1000);
        });
    });

</script>
<!-- start-smoth-scrolling -->
<!-- for-bottom-to-top smooth scrolling -->
<script type="text/javascript">
    $(document).ready(function () {
        /*
          var defaults = {
          containerID: 'toTop', // fading element id
          containerHoverID: 'toTopHover', // fading element hover id
          scrollSpeed: 1200,
          easingType: 'linear'
          };
        */
        jQuery(document).UItoTop({easingType: 'easeOutQuart'});
    });
</script>
<!-- Al inicio funcionaba, luego ya no más -->
<!--<a href="#" id="toTop" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>-->
<!-- Temporal Fix. It works -->
<a href="#home" id="toTop" class="scroll" style="display: block;">
  <span id="toTopHover" style="opacity: 1;"> </span></a>
<!-- //for-bottom-to-top smooth scrolling -->

<!-- menu-script -->
<script>
    (function ($) {
        // Menu Functions
        jQuery(document).ready(function () {

            $('#menuToggle').click(function (e) {
                var $parent = $(this).parent('.menu');
                $parent.toggleClass("open");
                var navState = $parent.hasClass('open') ? "hide" : "show";
                $(this).attr("title", navState + " navigation");
                // Set the timeout to the animation length in the CSS.
                setTimeout(function () {
                    console.log("timeout set");
                    $('#menuToggle > span').toggleClass("navClosed").toggleClass("navOpen");
                }, 200);
                e.preventDefault();
            });

            // OnMouseLeave for the sideBarNav (closing the menu when moving away the mouse)
            $('#sideBarNav').on('mouseleave', function () {
                var $menu = $('#menuToggle').parent('.menu');
                $menu.toggleClass("open");
                var navState = $menu.hasClass('open') ? "hide" : "show";
                $(this).attr("title", navState + " navigation");
                // Set the timeout to the animation length in the CSS.
                setTimeout(function () {
                    console.log("timeout set");
                    $('#menuToggle > span').toggleClass("navClosed").toggleClass("navOpen");
                }, 200);
                e.preventDefault();
            });

        });
    })($);
</script>
<!-- //menu-script -->

<!-- baneer-js -->
<!--<script src="app/javascript/packs/responsiveslides.min.js"></script>-->
<%#= javascript_pack_tag 'responsiveslides' %>
<script>
    // You can also use "$(window).load(function() {"
    jQuery(function () {
        // Slideshow 4
        jQuery("#slider").responsiveSlides({
            auto: true,
            pager: false,
            nav: false,
            speed: 500,
            namespace: "callbacks",
            before: function () {
                $('.events').append("<li>before event fired.</li>");
            },
            after: function () {
                $('.events').append("<li>after event fired.</li>");
            }
        });

    });
</script>
<!-- //baneer-js -->

<!-- skills -->
<!--<script src="app/javascript/packs/skill.bars.jquery.js"></script>-->
<%#= javascript_pack_tag 'skill.bars.jquery' %>
<script>
    jQuery(document).ready(function () {

        jQuery('.skillbar').skillBars({
            from: 0,
            speed: 4000,
            interval: 100,
            decimals: 0,
        });

    });
</script>
<!-- //skills -->

<!-- timeline -->
<!--<script type="text/javascript" src="app/javascript/packs/jquery.cntl.js"></script>-->
<script type="text/javascript">
    jQuery(document).ready(function (e) {
        jQuery('.cntl').cntl({
            revealbefore: 300,
            anim_class: 'cntl-animate',
            onreveal: function (e) {
                console.log(e);
            }
        });
    });
</script>
<!-- //timeline -->

<!-- accordion -->
<script>
    jQuery(document).ready(function () {
        function close_accordion_section() {
            jQuery('.accordion .accordion-section-title').removeClass('active');
            jQuery('.accordion .accordion-section-content').slideUp(300).removeClass('open');
        }

        jQuery('.accordion-section-title').click(function (e) {
            // Grab current anchor value
            var currentAttrValue = jQuery(this).attr('href');

            if (jQuery(e.target).is('.active')) {
                close_accordion_section();
            } else {
                close_accordion_section();

                // Add active class to section title
                jQuery(this).addClass('active');
                // Open up the hidden content panel
                jQuery('.accordion ' + currentAttrValue).slideDown(300).addClass('open');
            }

            e.preventDefault();
        });
    });
</script>
<!-- //accordion -->

<!-- for 'My Projects' Gallery -->
<%= javascript_pack_tag 'lightbox' %>
<script>
    $(document).ready(function () {
        // $('.cm-overlay').cmOverlay();
    });
</script>
<!-- //for projects -->

<!-- smooth scrolling -->
<!--<script src="app/javascript/packs/SmoothScroll.min.js"></script>-->
<%#= javascript_pack_tag 'SmoothScroll' %>
<!-- //smooth scrolling -->
<!-- //js-scripts -->
</body>
</html>

app/views/layouts/contacts.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SharpNotes 2020</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta property="og:image" content="<%= asset_path 'ruby-on-rails-logo.png' %>"/>
  <link rel="shortcut icon" href="<%= asset_path 'ruby-on-rails-logo.png' %>"/>

  <%= stylesheet_link_tag 'login' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body class="sb-nav-fixed">

<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
  <img class="ml-4" style="width: 41px; height: 43px;" src=<%= "#{asset_path 'ruby-on-rails-logo.png'}" %>>
  <%= link_to contacts_path, class: 'navbar-brand' do %>
    <span style="color: #0369D9; font-weight: bold;">Rey</span><span style="color: #bc3939; font-weight: bold;">Millenium</span>
  <% end %>
  <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i>
  </button>
  <div class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
  </div>
  <!-- Navbar-->
  <ul class="navbar-nav ml-auto ml-md-0">
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
        <% if user_signed_in? %>
          <%= link_to 'Edit profile', edit_user_registration_path, class: 'dropdown-item' %>
          <div class="dropdown-divider"></div>
          <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path, class: 'dropdown-item' %>
          <%= link_to "Login", new_user_session_path, class: 'dropdown-item' %>
        <% end %>
      </div>
    </li>
  </ul>
</nav>
<div id="layoutSidenav">
  <div id="layoutSidenav_nav">
    <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
      <div class="sb-sidenav-menu">
        <div class="nav">
          <div class="sb-sidenav-menu-heading">Dashboard</div>
          <%= link_to pages_path, class: 'nav-link' do %>
            <div class="sb-nav-link-icon"><i class="fas fa-briefcase"></i></div>
            Portfolio
          <% end %>

          <%= link_to contacts_path, class: 'nav-link' do %>
            <div class="sb-nav-link-icon"><i class="fas fa-envelope"></i></div>
            Messages
          <% end %>

          <%= link_to skills_path, class: 'nav-link' do %>
            <div class="sb-nav-link-icon"><i class="fas fa-cogs"></i></div>
            Skills
          <% end %>
        </div>
      </div>
      <div class="sb-sidenav-footer">
        <div class="small">Logged in as:</div>
        <% if user_signed_in? %>
          <div><%= current_user.email %></div>
        <% else %>
          Start Bootstrap
        <% end %>
      </div>
    </nav>
  </div>
  <div id="layoutSidenav_content">
    <main>
      <div class="container-fluid">
        <%= render("shared/flash_messages") %>
        <%= yield %>
      </div>
    </main>

    <footer class="py-4 bg-light mt-auto">
      <div class="container-fluid">
        <div class="d-flex align-items-center justify-content-between small">
          <div class="text-muted">&copy; <%= Time.now.year.to_s %>. All rights reserved | Developed by
            <%= link_to "https://www.linkedin.com/in/reymillenium/", class: "linkedin", target: '_linkedin' do %>
              Reinier Garcia
            <% end %>
          </div>
          <div>
            <a href="#">Privacy Policy</a>
            &middot;
            <a href="#">Terms &amp; Conditions</a>
          </div>
        </div>
      </div>
    </footer>
  </div>
</div>
<script src="app/javascript/packs/contacts/scripts.js"></script>
<script src="app/javascript/packs/contacts/chart-area-demo.js"></script>
<script src="app/javascript/packs/contacts/chart-bar-demo.js"></script>
<script src="app/javascript/packs/contacts/datatables-demo.js"></script>
<%#= javascript_pack_tag 'scripts' %>
</body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reinier Garcia: Ruby on Rails Developer</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link rel="shortcut icon" href="<%= asset_path 'ruby-on-rails-logo.png' %>"/>

  <%#= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  <%# if params[:controller] == 'post'  %>
  <%#= stylesheet_link_tag 'login.scss' %>
  <%# end %>
  <%= stylesheet_link_tag 'login' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body class="bg-secondary">
<div id="layoutAuthentication">
  <div id="layoutAuthentication_content">
    <main>
      <div class="container">
        <%= render("shared/flash_messages") %>
        <%= yield %>
      </div>
    </main>
  </div>
  <div id="layoutAuthentication_footer">
    <footer class="py-4 bg-light mt-auto">
      <div class="container-fluid">
        <div class="d-flex align-items-center justify-content-between small">
          <div class="text-muted">&copy; <%= Time.now.year.to_s %>. All rights reserved | Developed by
            <%= link_to "https://www.linkedin.com/in/reymillenium/", class: "linkedin", target: '_linkedin' do %>
              Reinier Garcia
            <% end %>
          </div>
          <div>
            <a href="#">Privacy Policy</a>
            &middot;
            <a href="#">Terms &amp; Conditions</a>
          </div>
        </div>
      </div>
    </footer>
  </div>
</div>
<%#= javascript_pack_tag 'scripts' %>
</body>
</html>